# Generated by Django 4.2.3 on 2023-08-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='media/Products-Avatar/'),
        ),
    ]
